export const employeeConstants = {
    ADD_REQUEST: 'EMPLOYEE_ADD_REQUEST',
    ADD_SUCCESS: 'EMPLOYEE_ADD_SUCCESS',
    ADD_FAILURE: 'EMPLOYEE_ADD_FAILURE',

    GETALL_REQUEST: 'EMPLOYEE_GETALL_REQUEST',
    GETALL_SUCCESS: 'EMPLOYEE_GETALL_SUCCESS',
    GETALL_FAILURE: 'EMPLOYEE_GETALL_FAILURE',

    DELETE_REQUEST: 'EMPLOYEE_DELETE_REQUEST',
    DELETE_SUCCESS: 'EMPLOYEE_DELETE_SUCCESS',
    DELETE_FAILURE: 'EMPLOYEE_DELETE_FAILURE',

    UPDATE_REQUEST: 'EMPLOYEE_UPDATE_REQUEST',
    UPDATE_SUCCESS: 'EMPLOYEE_UPDATE_SUCCESS',
    UPDATE_FAILURE: 'EMPLOYEE_UPDATE_FAILURE'
};
