export const fileUploadConstants = {
    ADD_REQUEST: 'FILEUPLOAD_ADD_REQUEST',
    ADD_SUCCESS: 'FILEUPLOAD_ADD_SUCCESS',
    ADD_FAILURE: 'FILEUPLOAD_ADD_FAILURE',

    GETALL_REQUEST: 'FILEUPLOAD_GETALL_REQUEST',
    GETALL_SUCCESS: 'FILEUPLOAD_GETALL_SUCCESS',
    GETALL_FAILURE: 'FILEUPLOAD_GETALL_FAILURE',

    DELETE_REQUEST: 'FILEUPLOAD_DELETE_REQUEST',
    DELETE_SUCCESS: 'FILEUPLOAD_DELETE_SUCCESS',
    DELETE_FAILURE: 'FILEUPLOAD_DELETE_FAILURE',

    UPDATE_REQUEST: 'FILEUPLOAD_UPDATE_REQUEST',
    UPDATE_SUCCESS: 'FILEUPLOAD_UPDATE_SUCCESS',
    UPDATE_FAILURE: 'FILEUPLOAD_UPDATE_FAILURE'
};
